---
title: "Brazil Survey"
#author: "JP"
#date: "June 9, 2017"
output: html_document
---

This survey provides primary evidence that the extension of guaranteed public benefits by Brazil's federal government over the past decade has empowered voters in local politics and helped to make politics more inclusive and programmatic. While many voters in Brazil's northeast have been subject to clientelist threats by politicians with monopoly control over public resources, voters who receive the Bolsa Familia conditional cash transfer "from Brasilia" are more confident that government will be responsive, more likely to reject hypothetical offers to buy their votes, and more likely to agree that government is run in the interests of all. 

These insights were made possible by an innovative household survey design that sampled 1,881 respondents in 27 municipalities in Alagoas, Bahia and Ceara states. The inferential method compares transfer recipients with those on the scheme's waiting list, permitting identification of the policy's effects, since both groups met the same eligibility criteria and differ in recipient status only due to idiosyncrasies in timing and implementation. The survey then used novel conjoint survey measures to measure citizens' expectations about others' attitudes, allowing the team to isolate the mechanism by which policies can shape local politics as a shift in citizens' mutual expectations. Respondents believed that hypothetical voters who received Bolsa Familia are substantially more likely to vote against clientelist candidates. Since voting against clientelism is a collective action problem in which each wishes to avoid the punishment of voting against a clientelist winner, confidence that other voters will vote for reform can provide a potential route out of the clientelist trap.