---
title: "My Research"
#author: "JP"
#date: "May 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My research agenda focuses on explaining the political roots of good governance; on
why some citizens are able to reliably access public services based on their needs and rights while others depend on political connections. Through subnational comparisons in my primary fieldwork sites in Brazil, Nigeria and India I seek to clarify the incentives that lead some politicians to focus on enforcing clear rules rather than diverting public resources to political supporters. Through innvoative survey designs and causal inference technique such as geographical regression discontinuities I seek to understand under what conditions citizens are empowered to vote freely and hold political elites accountable.

Research outputs to date explain how the unique circumstances of Tasso Jereissati's
elevation to the governor's office in Ceará in the 1980s explain subsequent improvements
in governance; why poor Indian voters consistently voted for reform in Bihar state while their counterparts in Jharkhand remained in a clientelist trap; and why polio vaccination in Northern Nigeria has empowered local communities to demand other public services from
the state.

I recently graduated with a PhD in Political Science at Harvard University's [Department of Government](http://gov.harvard.edu). Previously I worked with a phenomenal team of civil servants to guide investments in the MDGs within Nigeria's [Federal Government](http://www.nigeria.gov.ng/). I have also studied at [SOAS](https://www.soas.ac.uk/) and [New College](http://www.new.ox.ac.uk/), Oxford, worked for [Oxera](www.oxera.com/), and [Vivid Economics](http://www.vivideconomics.com/), consulted for DFID and the World Bank and interned for [Martin Horwood MP](http://www.martinhorwood.net/) in the UK Parliament.

###[CV](cv.pdf) -- [Lattes](http://lattes.cnpq.br/4097286915046638) -- [Google Scholar](https://scholar.google.ca/citations?hl=en&user=uHCbWZAAAAAJ&btnA=1&view_op=list_works&gmla=AJsN-F5iqpJZWBa3iYt08hG8wf-_iJuqp_nsY_7UhK2BlWCYvdjUiDyisHVovGGuFdPOfVGNDSk0kemkC5PNA2acF57ChJEg-6o5WperMK5_9Se6JpVzqE8) -- [Github](https://github.com/JonnyPhillips) -- [ORCID](http://www.orcid.org/0000-0002-3073-1045)

