--- 
title: "Publications"
output:
  html_document:
    css: "style.css"
---

### Political Economy of Development

- Phillips, J. (Forthcoming). Book Review: 'Decadent Developmentalism', Matthew
Taylor. Brazilian Political Science Review

- Artiz Prillaman, S. and Phillips, J. (2020). [How the Labor Force is Mobilized: Patterns in Informality, Political Networks, and Political Linkages in Brazil](https://www.worldscientific.com/doi/10.1142/9789811202315_0007). In Cariboni,
S. L., editor, Political Economy of Informality in BRIC Countries. World Scientific
Publishing.

- Phillips, J. (2017), [Can Bihar Break the Clientelist Trap? The Political Effects of Programmatic Development Policy](https://www.theigc.org/wp-content/uploads/2017/07/Phillips-2017-Working-paper.pdf), International Growth Centre Working Paper, S-34311-INB-1.  
    - [Ideas 4 India Blog](http://ideasforindia.in/article.aspx?article_id=2895)  
    - [International Growth Centre Blog](https://www.theigc.org/blog/breaking-clientelist-trap-creating-demand-good-governance-india/)  

- *[Working Paper]* Outsiders Against the Party Machine: Programmatic Reform in Subnational Democracies   
    - [Jota Blog](https://www.jota.info/opiniao-e-analise/colunas/cepesp/o-que-podemos-esperar-de-uma-nova-geracao-de-politicos-02022018)  

- *[Working Paper]* How Social Policy Undercuts the Appeal of Clientelism: Bolsa Familia, Policy Feedback and Collective Confidence

### Politics of Public Health

- Grossman, S., Phillips, J., & Rosenzweig, L. R. (2018). [Opportunistic Accountability : State-Society Bargaining Over Shared Interests](http://journals.sagepub.com/doi/metrics/10.1177/0010414017720706). Comparative Political Studies, 1-31  
    - [Monkey Cage, Washington Post](https://www.washingtonpost.com/news/monkey-cage/wp/2016/08/23/polio-is-back-in-nigeria-heres-why-local-communities-will-bargain-hard-on-the-next-vaccination-surge/?utm{\_}term=.4ebe68d195f6)

- Dhillon, R., & Phillips, J. (2015). [State Capability and Rwanda's Health Gains](https://doi.org/10.1016/S2214-109X(15)00008-X). Lancet Global Health. 

- *[Working Paper]* Legibility and State Capacity in Nigeria's Polio Campaign

### Corruption

- Avelino, G., Biderman, C., Bueno, N. S., Phillips, J., and Mesquita, L. (2019b). [The Power of Money in Electoral Campaigns](http://www.cepesp.io/publicacoes/7102/). CEPESP-FGV.

- Avelino, G., Biderman, C., Bueno, N. S., Phillips, J., and Mesquita, L. (2019a). [The Cost of Campaign Finance in Brazil: An Analysis Based on Evidence](http://www.cepesp.io/publicacoes/os-custos-da-campanha-eleitoral-no-brasil-uma-analise-baseada-em-evidencia/). CEPESP-FGV.

### Economics

- Diagne, A., Glover, S., Groom, B., & Phillips, J. (2012). [Africa's Green Revolution? Raising Awareness of New Rice Crops for Africa (NERICAs)](https://www.soas.ac.uk/economics/research/workingpapers/file76516.pdf). SOAS Department of Economics Working Paper Series 176.  
    - [World Financial Review](http://www.worldfinancialreview.com/?p=653)

- Phillips, J. and Ozegbe, N. (2010). "Challenges of the Global Financial and Economic Crisis for MDGs Spending and Policies in Nigeria" in "[The Global Economic Crisis and Nigeria: Taking the Right Lessons, Avoiding the Wrong Lessons](http://elibrary.nils.gov.ng:8080/newgenlibctxt/View?CatId=2281&OwnLibId=1&LibraryId=1&From=Library)", Editors: Eboh, Eric C. and Ogbu, Osita. African Institute for Applied Economics.

- Pan, J., Phillips, J., & Chen, Y. (2008). [China's Balance of Emissions Embodied in Trade: Approaches to Measurement and Allocating International Responsibility](https://doi.org/10.1093/oxrep/grn016). Oxford Review of Economic Policy, 24(2), 354-376. 

- Holt, D., Horncastle, A., and Phillips, J. (2006). [Capital Efficiency at Airports and Related Services](https://www.sciencedirect.com/science/article/abs/pii/S0957178706000373). Utilities Policy, 14(4):251-261.

